spring:
    profiles:
        active: ${APP_PROFILE:test}
    output:
        ansi:
            enabled: always
app:
    version: ${APP_VERSION:v1}
    secret: ${APP_SECRET:secret}
    img-directory: /dist/
springdoc:
    pathsToMatch:
        - /v1/**