spring:
    profiles:
        active: ${APP_PROFILE:test}
    output:
        ansi:
            enabled: always
    servlet:
        multipart:
            enabled: true
            max-file-size: 1MB
            max-request-size: 1MB
app:
    version: ${APP_VERSION:v1}
    secret: ${APP_SECRET:secret}
    img-directory: /app/assets/
springdoc:
    pathsToMatch:
        - /v1/**